version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain devops-projects --domain-owner 470296731356 --region ap-southeast-1 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on `date`
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging artifacts...
      - mvn -s settings.xml package
artifacts:
  files:
    - target/devops-cicd.war
  discard-paths: no
